### PR TITLE
use forked secure-random to add vue-cli support

### LINKED ISSUE #398: crypto.randomBytes is not a function
#### Expected behavior

Should be able to import steem library into my vue,js project.

#### Actual behavior

Getting the following error:
[Vue warn]: Error in mounted hook: "TypeError: crypto.randomBytes is not a function"
on the following line:
var steem = require('steem') 

The exception is thrown from the nodeRandom function in secure-random.js.
I put a breakpoint in that function and I can see that require('crypto') returns an empty object:

```console
> crypto
<- {}
```

#### How to reproduce

I seem to be able to reproduce the problem by just invoking:
require('steem')

The reported error is in secure-random.js, in the function nodeRandom.

I have verified that I can invoke the crypto.randomBytes function directly from my application.
The following works:
console.log(require('crypto').randomBytes(64))
so I'm wondering if the steem library somehow messes up crypto.

#### Environment information

Using node 8.10 on Ubuntu 18.04
Application uses the Quasar UI framework with vue.js.

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #398

https://github.com/steemit/steem-js/issues/398#issuecomment-412282289

### CODE REVIEW

**Comment by VIM-Arcange** [comment]
Can someone approve this pull request? It's a non breaking but useful fix!

If the use of a forked version of secure-random is an issue, why not integrate the fix directly into this project. Secure-random is a a one file library. Copying and using an updated version of `secure-random.js` should not so difficult.

**Comment by roadscape** [comment]
We should not use a forked version of secure-random. Is this something that can be fixed upstream?

**Comment by Sekhmet** [comment]
I've contacted the maintainer of secure-random today about this issue.

**Comment by Sekhmet** [comment]
A new version of `secure-random` has been released with a fix.
-> #441

**Comment by VIM-Arcange** [comment]
Thanks for the work you have done @Sekhmet 
@roadscape Can you review this PR?

**Pull request closed without merging**
