### PR TITLE
Use 'create-hash' and 'create-hmac' instead of 'crypto'

### PR DESCRIPTION
**Pull request by adcpm**
This change should fix an issue reported by @feruzm. 

image

### CODE REVIEW

**Comment by roadscape** [comment]
The changes look good to me, but I'm not familiar with this code. How's the test coverage on these lines?

**Comment by adcpm** [comment]
We have few tests that cover that functions changed like here:
https://github.com/steemit/steem-js/blob/58c567859c5d9d4e282c2e85d23e7145cb719935/test/KeyFormats.js 
This changes was inspired by @svk31 commit from steemjs-lib: https://github.com/svk31/steemjs-lib/commit/88e8855043792af3460a7c75414785fbb13eb681
These deps are being used to port node.js default crypto equivalent functions to browser: https://www.npmjs.com/package/crypto-browserify

**Comment by feruzm** [comment]
I would suggest to even go further and remove all usage of `crypto`, use `crypto-js` library with specific functions. 

crypto functions are used only in hash.js and aes.js

In aes.js

```
var AES = require("crypto-js/aes");
var encHex = require("crypto-js/enc-hex");
var encBase64 = require("crypto-js/enc-base64");
```

**Comment by adcpm** [comment]
I've removed the dep "crypto" completely. For aes.js i've used "browserify-aes" instead of "crypto-js" mainly because it's using same functions as "crypto" and it's been used by "crypto-browserify" which seem to be the main ported version of "crypto" used. Test "memo.test.js" use aes.js functions and pass without error and steem.min.js file is little smaller. It seem that if we are using "crypto" dep, some apps with different bundler like Ionic will use a different ported version of "crypto" for the browser, sometimes with outdated version.

**Pull request merged**
